name: Build main

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        default: "0.0.0"
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: |
        dotnet workload restore --ignore-failed-sources --skip-sign-check

    - name: Pack
      run: dotnet pack src/MongoDB.EntityFrameworkCore/MongoDB.EntityFrameworkCore.csproj -c Release -p:PackageVersion='${{ github.event.inputs.version }}' --include-symbols --output packages

    - name: Upload to GitHub registry
      run: |
        dotnet nuget add source --username julian-baumann --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/julian-baumann/index.json"
        dotnet nuget push "packages/MongoDB.EntityFrameworkCore.${{ github.event.inputs.version }}.nupkg" --api-key "${{ secrets.GITHUB_TOKEN }}" --source "github"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-Package
        path: packages
